export class Profile{
    username: string;
    dob: string
    phone: number
    website: string
    image: string
    country: string
    County: string
    City: string
    Estate: string
    bio: string
    extra_services: string
    gender: string
    sexual_orientation: string
    ethnicity: string
    hair_color: string
    hair_length: string
    bust_size: string
    build: string
    looks: string
    incall: boolean
    outcall: boolean
    smoker: boolean
    education_level: string
    hobbies: string
    sevices: string
    language_1: string
    language_2: string
    language_3: string
    language_1_fluency: string
    language_2_fluency: string
    language_3_fluency: string
}